### ISSUE TITLE
PA Review: Listings

### ISSUE THREAD

**Issue by xiaoyuny** [xiaoyuny/Airquq#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] All listings are publicly viewable, with an index page and show page

**Comment by xnanodax** [comment]
Great work on the styling!
- [ ] After I search for a city, I see their listing index items have different styling.
Airquq:
![screen shot 2018-10-17 at 9 50 05 am](https://user-images.githubusercontent.com/20424731/47102768-6d3ff900-d1f2-11e8-8af1-0a05ffefa5c4.png)

Airbnb:
![screen shot 2018-10-17 at 9 50 14 am](https://user-images.githubusercontent.com/20424731/47102811-89439a80-d1f2-11e8-8672-8d4651d5a07f.png)

- [ ] Let's the PREV and NEXT to arrows for the pictures! Let's also change the color of the little dots from black to white.
Airquq:
![screen shot 2018-10-17 at 9 55 07 am](https://user-images.githubusercontent.com/20424731/47102937-e8091400-d1f2-11e8-8ef4-2f0d9895b836.png)
Airbnb:
![screen shot 2018-10-17 at 9 55 39 am](https://user-images.githubusercontent.com/20424731/47102945-ee978b80-d1f2-11e8-9973-8eb06edb42ca.png)

- [ ] Let's get all of the positioning closer to airbnb!
airquq:
![screen shot 2018-10-17 at 9 58 37 am](https://user-images.githubusercontent.com/20424731/47103094-4930e780-d1f3-11e8-9561-8a7868b55fbb.png)

airbnb:
![screen shot 2018-10-17 at 9 58 39 am](https://user-images.githubusercontent.com/20424731/47103101-4df59b80-d1f3-11e8-9a54-d78e6d5cc679.png)

- [ ] Love the styling of the `/listings` page! Let's make it even closer to airbnb :)! Consider having 4 homes per row instead of 5.

**Comment by xiaoyuny** [comment]
I don't know why but Airbnb seems to have different versions of how they present the same page! This is what I see when I search Los Angeles Homes:

<img width="1590" alt="screen shot 2018-10-17 at 9 58 25 am" src="https://user-images.githubusercontent.com/41597756/47103070-3e765280-d1f3-11e8-8827-0b3f0a2699c5.png">

**Comment by xnanodax** [comment]
Interesting! How did you get to that page AND do you have a link?


This is the page I get: 
https://www.airbnb.com/s/Los-Angeles--CA--United-States/homes?refinement_paths%5B%5D=%2Fhomes&query=Los%20Angeles%2C%20CA%2C%20United%20States&allow_override%5B%5D=&s_tag=zM2W6Sct

**Comment by xiaoyuny** [comment]
I opened your link in an incognito tab and I saw the the page presented like the screenshot you sent earlier! But if I open it in a regular tab it looks like my screenshot.. Also I had never seen the splash page with a full-screen picture and search form before Carly told me to open Airbnb in an incognito tab! They seem to have different styling for regular and incognito tabs..
